import { beautyNews } from '../data/beautyNews'
import { digitalNews } from '../data/digitalNews'
import { luxuryNews } from '../data/luxuryNews'
import { sportsNews } from '../data/sportsNews'
import { webgamesNews } from '../data/webgamesNews'
import type { Story } from '../data/types'
import type { BrandSourceRule } from './types'

const coreBrandSources: BrandSourceRule[] = [
  {
    brand: 'PacoGames',
    category: 'webgames',
    subcategory: '新游',
    region: 'cn',
    sourceType: 'Official Site',
    listUrl: 'https://www.pacogames.com/latest-games',
    sourceLabel: 'PacoGames Latest Games',
    fetchMode: 'html',
    products: ['Pong', 'Tetris', 'PacoGames 最新游戏'],
    keywords: ['Latest games', 'Pong', 'PacoGames', 'new'],
    imageStrategy: 'product-page',
    cadence: 'wed-sun-twice',
    enabled: true,
  },
  {
    brand: 'GamePix',
    category: 'webgames',
    subcategory: '新游',
    region: 'cn',
    sourceType: 'Official Site',
    listUrl: 'https://www.gamepix.com/new',
    sourceLabel: 'GamePix New Games',
    fetchMode: 'html',
    products: ['The Crossing Master', 'Hill Survival Shooting Game', 'GamePix 新游戏'],
    keywords: ['New Games', 'The Crossing Master', 'GamePix', 'new'],
    imageStrategy: 'product-page',
    cadence: 'wed-sun-twice',
    enabled: true,
  },
  {
    brand: 'Poki',
    category: 'webgames',
    subcategory: '新游',
    region: 'cn',
    sourceType: 'Official Site',
    listUrl: 'https://poki.com/en/new',
    sourceLabel: 'Poki New Games',
    fetchMode: 'html',
    products: ['Bubble Tower', 'Count War', 'Snacky Snake'],
    keywords: ['New Games', 'Bubble Tower', 'Poki', 'new'],
    imageStrategy: 'product-page',
    cadence: 'wed-sun-twice',
    enabled: true,
  },
  {
    brand: 'Y8',
    category: 'webgames',
    subcategory: '新游',
    region: 'cn',
    sourceType: 'Official Site',
    listUrl: 'https://www.y8.com/new/games',
    sourceLabel: 'Y8 New Games',
    fetchMode: 'html',
    products: ['Cat Rescue', 'Foc Drag Street', 'Y8 新游戏'],
    keywords: ['New Games', 'Cat Rescue', 'Y8', 'new'],
    imageStrategy: 'product-page',
    cadence: 'wed-sun-twice',
    enabled: true,
  },
  {
    brand: 'CrazyGames',
    category: 'webgames',
    subcategory: '新游',
    region: 'cn',
    sourceType: 'Official Site',
    listUrl: 'https://www.crazygames.com/new',
    sourceLabel: 'CrazyGames New',
    fetchMode: 'html',
    products: ['Trash Master', 'Bills Must Be Paid', 'Mad Pursuit'],
    keywords: ['New games', 'Trash Master', 'CrazyGames', 'new'],
    imageStrategy: 'product-page',
    cadence: 'wed-sun-twice',
    enabled: true,
  },
  {
    brand: 'Arcadrome',
    category: 'webgames',
    subcategory: '新游',
    region: 'cn',
    sourceType: 'Official Site',
    listUrl: 'https://arcadrome.com/',
    sourceLabel: 'Arcadrome 首页新游',
    fetchMode: 'html',
    products: ['Lunar Knight', 'Idle Lumber Inc', 'Endless Waves Survival'],
    keywords: ['Arcadrome', 'Lunar Knight', 'new game', 'homepage'],
    imageStrategy: 'product-page',
    cadence: 'wed-sun-twice',
    enabled: true,
  },
  {
    brand: 'Louis Vuitton',
    category: 'luxury',
    subcategory: '服装',
    region: 'cn',
    sourceType: 'New Arrivals',
    listUrl: 'https://www.louisvuitton.cn/zhs-cn/women/new-in-women/_/N-ty7er6l',
    sourceLabel: 'Louis Vuitton 中国官网女士新品',
    fetchMode: 'html',
    products: ['LV Sneakerina', '露跟鞋', '女士新品'],
    keywords: ['新品系列', '女士', 'the latest', 'LV Sneakerina'],
    imageStrategy: 'product-page',
    cadence: 'wed-sun-twice',
    enabled: true,
  },
  {
    brand: 'Louis Vuitton',
    category: 'luxury',
    subcategory: '包袋',
    region: 'cn',
    sourceType: 'New Arrivals',
    listUrl: 'https://www.louisvuitton.cn/zhs-cn/men/new-in-men/_/N-t14l5lul',
    sourceLabel: 'Louis Vuitton 中国官网男士新品',
    fetchMode: 'html',
    products: ['Keepall Bandoulière 25', '手袋', '男士新品'],
    keywords: ['新品系列', '男士', 'the latest', 'Keepall'],
    imageStrategy: 'product-page',
    cadence: 'wed-sun-twice',
    enabled: true,
  },
  {
    brand: 'Louis Vuitton',
    category: 'luxury',
    subcategory: '夏季系列',
    region: 'cn',
    sourceType: 'Official Site',
    listUrl: 'https://www.louisvuitton.cn/zhs-cn/women/high-summer/_/N-t6p07xp',
    sourceLabel: 'LV High Summer 系列',
    fetchMode: 'html',
    products: ['High Summer', 'Neverfull BB LV&I', 'All In BB', 'LV Pearly Confetti'],
    keywords: ['High Summer', 'LV&I', '夏季', '度假'],
    imageStrategy: 'product-page',
    cadence: 'daily',
    enabled: true,
  },
  {
    brand: 'Louis Vuitton',
    category: 'luxury',
    subcategory: '线上首发',
    region: 'cn',
    sourceType: 'Official Site',
    listUrl: 'https://www.louisvuitton.cn/zhs-cn/men/sports-capsule/_/N-t1oxl8c0',
    sourceLabel: 'LV Sports 胶囊系列',
    fetchMode: 'html',
    products: ['LV Trainer', 'Sports', '护照套', 'LV Dragonne Sport'],
    keywords: ['Sports', 'LV Trainer', '运动鞋', '线上首发'],
    imageStrategy: 'product-page',
    cadence: 'daily',
    enabled: true,
  },
  {
    brand: 'Louis Vuitton',
    category: 'luxury',
    subcategory: '时装秀',
    region: 'cn',
    sourceType: 'Official Site',
    listUrl: 'https://www.louisvuitton.cn/zhs-cn/men/fall-winter-2026-show/_/N-t1g31ztu',
    sourceLabel: 'LV 秋冬男士 2026 系列',
    fetchMode: 'html',
    products: ['秋冬男士', 'FW 2026', 'Keepall', 'Courrier'],
    keywords: ['秋冬', 'FW 2026', '男士', '时装秀'],
    imageStrategy: 'product-page',
    cadence: 'daily',
    enabled: true,
  },
  {
    brand: 'Louis Vuitton',
    category: 'luxury',
    subcategory: '包袋',
    region: 'cn',
    sourceType: 'Official Site',
    listUrl: 'https://www.louisvuitton.cn/zhs-cn/women/handbags/new-in-handbags/_/N-t1dzbzff',
    sourceLabel: 'LV 女士当季新品包袋',
    fetchMode: 'html',
    products: ['Speedy Soft 30', 'All In BB', 'Multipass', 'Side Trunk'],
    keywords: ['当季新品', '手袋', '女士', 'new in'],
    imageStrategy: 'product-page',
    cadence: 'daily',
    enabled: true,
  },
  {
    brand: 'Louis Vuitton',
    category: 'luxury',
    subcategory: '包袋',
    region: 'cn',
    sourceType: 'Official Site',
    listUrl: 'https://www.louisvuitton.cn/zhs-cn/women/handbags/all-handbags/speedy/_/N-tfr7qdp-ak5wlig',
    sourceLabel: 'LV Speedy 手袋',
    fetchMode: 'html',
    products: ['Speedy', 'Bandoulière', 'Monogram', '手袋'],
    keywords: ['Speedy', '经典', 'Monogram', '手袋'],
    imageStrategy: 'product-page',
    cadence: 'daily',
    enabled: true,
  },
  {
    brand: 'Louis Vuitton',
    category: 'luxury',
    subcategory: '包袋',
    region: 'cn',
    sourceType: 'Official Site',
    listUrl: 'https://www.louisvuitton.cn/zhs-cn/women/handbags/all-handbags/neverfull/_/N-tfr7qdp-akyxcuct',
    sourceLabel: 'LV Neverfull 手袋',
    fetchMode: 'html',
    products: ['Neverfull', '中号', '大号', 'BB'],
    keywords: ['Neverfull', '经典', '托特包', '手袋'],
    imageStrategy: 'product-page',
    cadence: 'daily',
    enabled: true,
  },
  {
    brand: 'Louis Vuitton',
    category: 'luxury',
    subcategory: '包袋',
    region: 'cn',
    sourceType: 'Official Site',
    listUrl: 'https://www.louisvuitton.cn/zhs-cn/women/handbags/all-handbags/alma/_/N-tfr7qdp-aks0ott8',
    sourceLabel: 'LV Alma 手袋',
    fetchMode: 'html',
    products: ['Alma', 'Alma BB', 'Epi', '手袋'],
    keywords: ['Alma', '经典', '手袋', 'Epi'],
    imageStrategy: 'product-page',
    cadence: 'daily',
    enabled: true,
  },
  {
    brand: 'Louis Vuitton',
    category: 'luxury',
    subcategory: '包袋',
    region: 'cn',
    sourceType: 'Official Site',
    listUrl: 'https://www.louisvuitton.cn/zhs-cn/women/handbags/all-handbags/side-trunk/_/N-tfr7qdp-ak1ucxhxs',
    sourceLabel: 'LV Side Trunk 手袋',
    fetchMode: 'html',
    products: ['Side Trunk', '中号', 'MM', 'Monogram'],
    keywords: ['Side Trunk', '手袋', '经典', 'Monogram'],
    imageStrategy: 'product-page',
    cadence: 'daily',
    enabled: true,
  },
  {
    brand: 'Hermes',
    category: 'luxury',
    subcategory: '腕表',
    region: 'cn',
    sourceType: 'Official Site',
    listUrl: 'https://www.hermes.cn/cn/zh/content/322394-hermes-h08/',
    sourceLabel: '爱马仕中国官网 H08 腕表专题',
    fetchMode: 'browser',
    products: ['Hermes H08', 'Arceau', 'Cape Cod'],
    keywords: ['腕表', '新品', 'H08', 'Arceau', 'Cape Cod'],
    imageStrategy: 'page-screenshot',
    cadence: 'wed-sun-twice',
    enabled: true,
  },
  {
    brand: 'Hermes',
    category: 'luxury',
    subcategory: '女士鞋履',
    region: 'cn',
    sourceType: 'Official Site',
    listUrl: 'https://www.hermes.cn/cn/zh/category/%E5%A5%B3%E5%A3%AB/%E9%9E%8B%E5%B1%A5/%E6%89%80%E6%9C%89%E7%B3%BB%E5%88%97/#country=cn&fh_location=--%2Fcategories%3C%7Bwomenshoesviewall%7D',
    sourceLabel: '爱马仕中国官网女士鞋履全系列',
    fetchMode: 'browser',
    products: ['Neon运动鞋', 'Nectar芭蕾舞鞋', 'Nicoletta高跟鞋', 'Master运动鞋'],
    keywords: ['女士', '鞋履', 'Neon', 'Nectar', 'Nicoletta'],
    imageStrategy: 'product-page',
    cadence: 'wed-sun-twice',
    enabled: true,
  },
  {
    brand: 'Hermes',
    category: 'luxury',
    subcategory: '男士鞋履',
    region: 'cn',
    sourceType: 'Official Site',
    listUrl: 'https://www.hermes.cn/cn/zh/category/%E7%94%B7%E5%A3%AB/%E9%9E%8B%E5%B1%A5/%E6%89%80%E6%9C%89%E7%B3%BB%E5%88%97/#country=cn&fh_location=--%2Fcategories%3C%7Bmenshoesviewall%7D',
    sourceLabel: '爱马仕中国官网男士鞋履全系列',
    fetchMode: 'browser',
    products: ['Jackson凉鞋', 'Neon运动鞋', 'Next运动鞋', 'Chypre凉鞋'],
    keywords: ['男士', '鞋履', 'Jackson', 'Next', 'Chypre'],
    imageStrategy: 'product-page',
    cadence: 'wed-sun-twice',
    enabled: true,
  },
  {
    brand: 'Hermes',
    category: 'luxury',
    subcategory: '皮包',
    region: 'cn',
    sourceType: 'Official Site',
    listUrl: 'https://www.hermes.cn/cn/zh/category/%E7%9A%AE%E5%85%B7/%E5%B0%8F%E7%9A%AE%E5%85%B7/to-go%E9%92%B1%E5%8C%85/#country=cn&fh_location=--%2Fcategories%3C%7Bsmallleathergoodstogowallets%7D',
    sourceLabel: '爱马仕中国官网小皮具To-Go钱包',
    fetchMode: 'browser',
    products: ['Constance To Go', 'Kelly To Go', 'Roulis Slim'],
    keywords: ['小皮具', 'To Go', '钱包', 'Constance', 'Kelly'],
    imageStrategy: 'product-page',
    cadence: 'wed-sun-twice',
    enabled: true,
  },
  {
    brand: 'Hermes',
    category: 'luxury',
    subcategory: '丝巾',
    region: 'cn',
    sourceType: 'Official Site',
    listUrl: 'https://www.hermes.cn/cn/zh/category/women/scarves-shawls-and-stoles/view-all/#country=cn&fh_location=--%2Fcategories%3C%7Bwomensilkall%7D',
    sourceLabel: '爱马仕中国官网女士丝巾全系列',
    fetchMode: 'browser',
    products: ['90x90厘米丝巾', 'Twilly', '140x140披肩'],
    keywords: ['丝巾', 'Twilly', '披肩', '女士'],
    imageStrategy: 'product-page',
    cadence: 'wed-sun-twice',
    enabled: true,
  },
  {
    brand: 'Hermes',
    category: 'luxury',
    subcategory: '时尚首饰',
    region: 'cn',
    sourceType: 'Official Site',
    listUrl: 'https://www.hermes.cn/cn/zh/category/women/fashion-jewelry/view-all/#country=cn&fh_location=--%2Fcategories%3C%7Bwomenjewelryall%7D',
    sourceLabel: '爱马仕中国官网女士时尚首饰全系列',
    fetchMode: 'browser',
    products: ['Mini Clic Kelly', 'Collier de Chien', 'Clic H'],
    keywords: ['首饰', 'Clic', '手镯', '项链'],
    imageStrategy: 'product-page',
    cadence: 'wed-sun-twice',
    enabled: true,
  },
  {
    brand: 'Hermes',
    category: 'luxury',
    subcategory: '家居与生活艺术',
    region: 'cn',
    sourceType: 'Official Site',
    listUrl: 'https://www.hermes.cn/cn/en/category/home/textiles/',
    sourceLabel: '爱马仕中国官网家居与生活艺术',
    fetchMode: 'browser',
    products: ['Avalon毛毯', 'H Déco餐瓷', 'Mosaique au 24餐盘', "Cheval d'Orient茶具"],
    keywords: ['家居', '生活艺术', '餐瓷', '毛毯', '装饰'],
    imageStrategy: 'product-page',
    cadence: 'wed-sun-twice',
    enabled: true,
  },
  {
    brand: 'Hermes',
    category: 'luxury',
    subcategory: '经典手袋',
    region: 'cn',
    sourceType: 'Official Site',
    listUrl: 'https://www.hermes.cn/cn/en/category/leather-goods/',
    sourceLabel: '爱马仕中国官网经典手袋',
    fetchMode: 'browser',
    products: ['Birkin手袋', 'Kelly手袋', 'Lindy手袋', 'Picotin Lock'],
    keywords: ['手袋', '皮包', 'Birkin', 'Kelly', 'Lindy', 'Picotin'],
    imageStrategy: 'product-page',
    cadence: 'wed-sun-twice',
    enabled: true,
  },
  {
    brand: 'Hermes',
    category: 'luxury',
    subcategory: '女士凉鞋',
    region: 'cn',
    sourceType: 'Official Site',
    listUrl: 'https://www.hermes.cn/cn/en/category/women/shoes/',
    sourceLabel: '爱马仕中国官网女士凉鞋',
    fetchMode: 'browser',
    products: ['Oran凉鞋', 'Oasis凉鞋', 'Legend凉鞋'],
    keywords: ['女士', '凉鞋', 'Oran', 'Oasis', 'Legend'],
    imageStrategy: 'product-page',
    cadence: 'wed-sun-twice',
    enabled: true,
  },
  {
    brand: 'Prada',
    category: 'luxury',
    subcategory: '包袋',
    region: 'cn',
    sourceType: 'Official Site',
    listUrl: 'https://www.prada.cn/cn/zh/womens/new-in/c/10111CN',
    sourceLabel: 'Prada 中国官网女士新品页',
    fetchMode: 'html',
    products: ['Prada Passage中号皮革手袋', 'Prada Bonnie 中号印花亚麻皮革拼接手提包', 'Prada Carry 迷你皮革手袋'],
    keywords: ['Prada', '女士新品上市', '包袋', 'Prada Galleria'],
    imageStrategy: 'product-page',
    cadence: 'wed-sun-twice',
    enabled: true,
  },
  {
    brand: 'Prada',
    category: 'luxury',
    subcategory: '服装',
    region: 'cn',
    sourceType: 'Official Site',
    listUrl: 'https://www.prada.cn/cn/zh/womens/new-in/c/10111CN',
    sourceLabel: 'Prada 中国官网女士新品页',
    fetchMode: 'html',
    products: ['蕾丝连衣裙', 'Re-Nylon 半身裙', '斜纹棉布中长半身伞裙'],
    keywords: ['Prada', '女士新品上市', '服装', '2026春夏'],
    imageStrategy: 'product-page',
    cadence: 'wed-sun-twice',
    enabled: true,
  },
  {
    brand: 'Prada',
    category: 'luxury',
    subcategory: '首饰',
    region: 'cn',
    sourceType: 'Official Site',
    listUrl: 'https://www.prada.cn/cn/zh/fine-jewelry/eternal-gold/c/10763CN',
    sourceLabel: 'Prada 中国官网 Eternal Gold 系列',
    fetchMode: 'html',
    products: ['Eternal Gold中号吊坠项链', 'Prada Symbole 项链', 'Prada Fine Jewelry'],
    keywords: ['Prada', '首饰', 'Eternal Gold', 'Fine Jewelry'],
    imageStrategy: 'product-page',
    cadence: 'wed-sun-twice',
    enabled: true,
  },
  {
    brand: 'Prada',
    category: 'luxury',
    subcategory: '鞋履',
    region: 'cn',
    sourceType: 'Official Site',
    listUrl: 'https://www.prada.cn/cn/zh/womens/shoes/c/10070CN',
    sourceLabel: 'Prada 中国官网女士鞋履',
    fetchMode: 'html',
    products: ['Prada Monolith', 'Prada Americas Cup', 'Prada 乐福鞋'],
    keywords: ['Prada', '鞋履', 'Monolith', '乐福鞋'],
    imageStrategy: 'product-page',
    cadence: 'wed-sun-twice',
    enabled: true,
  },
  {
    brand: 'Prada',
    category: 'luxury',
    subcategory: '男士新品',
    region: 'cn',
    sourceType: 'Official Site',
    listUrl: 'https://www.prada.cn/cn/zh/mens/new-in/c/10182CN',
    sourceLabel: 'Prada 中国官网男士新品',
    fetchMode: 'html',
    products: ['Prada 男装', 'Prada 男鞋', 'Prada 男包'],
    keywords: ['Prada', '男士', '新品', 'men'],
    imageStrategy: 'product-page',
    cadence: 'wed-sun-twice',
    enabled: true,
  },
  {
    brand: 'Prada',
    category: 'luxury',
    subcategory: '夏季系列',
    region: 'cn',
    sourceType: 'Official Site',
    listUrl: 'https://www.prada.cn/cn/zh/womens/days-of-summer/c/10996CN',
    sourceLabel: 'Prada Days of Summer 女士',
    fetchMode: 'html',
    products: ['Prada 夏季', 'Days of Summer', '女装', '女鞋', '女包'],
    keywords: ['Prada', '夏季', 'Days of Summer', '女装', '度假'],
    imageStrategy: 'product-page',
    cadence: 'daily',
    enabled: true,
  },
  {
    brand: 'Prada',
    category: 'luxury',
    subcategory: '夏季系列',
    region: 'cn',
    sourceType: 'Official Site',
    listUrl: 'https://www.prada.cn/cn/zh/mens/days-of-summer/c/10997CN',
    sourceLabel: 'Prada Days of Summer 男士',
    fetchMode: 'html',
    products: ['Prada 夏季', 'Days of Summer', '男装', '男鞋', '男包'],
    keywords: ['Prada', '夏季', 'Days of Summer', '男装', '度假'],
    imageStrategy: 'product-page',
    cadence: 'daily',
    enabled: true,
  },
  {
    brand: 'Prada',
    category: 'luxury',
    subcategory: '包袋',
    region: 'cn',
    sourceType: 'Official Site',
    listUrl: 'https://www.prada.cn/cn/zh/womens/essentials/prada-route/c/10990CN',
    sourceLabel: 'Prada Route 系列手袋',
    fetchMode: 'html',
    products: ['Prada Route', '大号', '中号', '皮革'],
    keywords: ['Prada Route', '手袋', '皮革', '托特包'],
    imageStrategy: 'product-page',
    cadence: 'daily',
    enabled: true,
  },
  {
    brand: 'Prada',
    category: 'luxury',
    subcategory: '包袋',
    region: 'cn',
    sourceType: 'Official Site',
    listUrl: 'https://www.prada.cn/cn/zh/womens/essentials/prada-bonnie/c/10758CN',
    sourceLabel: 'Prada Bonnie 系列手袋',
    fetchMode: 'html',
    products: ['Prada Bonnie', '中号', '亚麻', '印花'],
    keywords: ['Prada Bonnie', '手袋', '亚麻', '印花'],
    imageStrategy: 'product-page',
    cadence: 'daily',
    enabled: true,
  },
  {
    brand: 'Prada',
    category: 'luxury',
    subcategory: '包袋',
    region: 'cn',
    sourceType: 'Official Site',
    listUrl: 'https://www.prada.cn/cn/zh/womens/essentials/prada-carry/c/11076CN',
    sourceLabel: 'Prada Carry 系列手袋',
    fetchMode: 'html',
    products: ['Prada Carry', '迷你', '皮革', 'Saffiano'],
    keywords: ['Prada Carry', '手袋', '迷你', 'Saffiano'],
    imageStrategy: 'product-page',
    cadence: 'daily',
    enabled: true,
  },
  {
    brand: 'Prada',
    category: 'luxury',
    subcategory: '包袋',
    region: 'cn',
    sourceType: 'Official Site',
    listUrl: 'https://www.prada.cn/cn/zh/mens/essentials/prada-brique/c/11047CN',
    sourceLabel: 'Prada Brique 男包',
    fetchMode: 'html',
    products: ['Prada Brique', '男包', '斜挎', 'Saffiano'],
    keywords: ['Prada Brique', '男包', '斜挎', 'Saffiano'],
    imageStrategy: 'product-page',
    cadence: 'daily',
    enabled: true,
  },
  {
    brand: 'Prada',
    category: 'luxury',
    subcategory: '珠宝',
    region: 'cn',
    sourceType: 'Official Site',
    listUrl: 'https://www.prada.cn/cn/zh/fine-jewelry/couleur-vivante/c/10785CN',
    sourceLabel: 'Prada Couleur Vivante 珠宝',
    fetchMode: 'html',
    products: ['Couleur Vivante', 'Fine Jewelry', '黄金', '彩色宝石'],
    keywords: ['Prada', 'Couleur Vivante', '珠宝', 'Fine Jewelry', '彩色宝石'],
    imageStrategy: 'product-page',
    cadence: 'daily',
    enabled: true,
  },
  {
    brand: 'Prada',
    category: 'luxury',
    subcategory: '鞋履',
    region: 'cn',
    sourceType: 'Official Site',
    listUrl: 'https://www.prada.cn/cn/zh/mens/shoes/americas-cup/c/10297CN',
    sourceLabel: 'Prada America\'s Cup 男鞋',
    fetchMode: 'html',
    products: ['America\'s Cup', '运动鞋', '男鞋', '皮革'],
    keywords: ['Prada', 'Americas Cup', '男鞋', '运动鞋'],
    imageStrategy: 'product-page',
    cadence: 'daily',
    enabled: true,
  },
  {
    brand: 'Valentino',
    category: 'luxury',
    subcategory: '包袋',
    region: 'cn',
    sourceType: 'Official Site',
    listUrl: 'https://www.valentino.cn/zh-cn/women/bags/',
    sourceLabel: 'Valentino 中国官网·女士包袋',
    fetchMode: 'html',
    products: ['Garavani Loc 手袋', 'Valentino Garavani', 'VLogo 手袋'],
    keywords: ['Valentino', 'Garavani', 'Loc', '手袋', '包袋'],
    imageStrategy: 'product-page',
    cadence: 'daily',
    enabled: true,
  },
  {
    brand: 'Valentino',
    category: 'luxury',
    subcategory: '包袋',
    region: 'cn',
    sourceType: 'Official Site',
    listUrl: 'https://www.valentino.cn/zh-cn/women/bags/',
    sourceLabel: 'Valentino 中国官网·女士包袋',
    fetchMode: 'html',
    products: ['VLogo 手袋', 'Valentino Garavani', '皮革手袋'],
    keywords: ['Valentino', 'VLogo', '手袋', '包袋'],
    imageStrategy: 'product-page',
    cadence: 'daily',
    enabled: true,
  },
  {
    brand: 'Valentino',
    category: 'luxury',
    subcategory: '鞋履',
    region: 'cn',
    sourceType: 'Official Site',
    listUrl: 'https://www.valentino.cn/zh-cn/women/shoes/',
    sourceLabel: 'Valentino 中国官网女士鞋履',
    fetchMode: 'html',
    products: ['Valentino Garavani 鞋履', 'Rockstud 铆钉鞋', 'Tan-Go 高跟鞋'],
    keywords: ['Valentino', '鞋履', 'Rockstud', '高跟鞋'],
    imageStrategy: 'product-page',
    cadence: 'daily',
    enabled: true,
  },
  {
    brand: 'Valentino',
    category: 'luxury',
    subcategory: '成衣',
    region: 'cn',
    sourceType: 'Official Site',
    listUrl: 'https://www.valentino.cn/zh-cn/women/ready-to-wear/',
    sourceLabel: 'Valentino 中国官网女士成衣',
    fetchMode: 'html',
    products: ['Valentino 成衣', '连衣裙', '外套'],
    keywords: ['Valentino', '成衣', 'Ready-to-Wear', '连衣裙'],
    imageStrategy: 'product-page',
    cadence: 'daily',
    enabled: true,
  },
  {
    brand: 'Cartier',
    category: 'luxury',
    subcategory: '首饰',
    region: 'cn',
    sourceType: 'Official Site',
    listUrl: 'https://www.cartier.cn/zh-cn/collections/jewelry/',
    sourceLabel: '卡地亚中国官网·LOVE 系列',
    fetchMode: 'html',
    products: ['LOVE 手链', 'LOVE 戒指', 'LOVE 项链'],
    keywords: ['Cartier', 'LOVE', '手链', '戒指', '18K'],
    imageStrategy: 'product-page',
    cadence: 'daily',
    enabled: true,
  },
  {
    brand: 'Cartier',
    category: 'luxury',
    subcategory: '腕表',
    region: 'cn',
    sourceType: 'Official Site',
    listUrl: 'https://www.cartier.cn/zh-cn/collections/watches/',
    sourceLabel: '卡地亚中国官网·Panthère de Cartier 腕表',
    fetchMode: 'html',
    products: ['Panthère de Cartier', 'Tank Française', 'Santos de Cartier'],
    keywords: ['Cartier', 'Panthère', '腕表', 'Tank'],
    imageStrategy: 'product-page',
    cadence: 'daily',
    enabled: true,
  },
  {
    brand: 'Cartier',
    category: 'luxury',
    subcategory: '首饰',
    region: 'cn',
    sourceType: 'Official Site',
    listUrl: 'https://www.cartier.cn/zh-cn/collections/jewelry/',
    sourceLabel: '卡地亚中国官网·Trinity 系列',
    fetchMode: 'html',
    products: ['Trinity 戒指', 'Trinity 手链', 'Trinity 项链'],
    keywords: ['Cartier', 'Trinity', '三色金', '戒指'],
    imageStrategy: 'product-page',
    cadence: 'daily',
    enabled: true,
  },
  {
    brand: 'Cartier',
    category: 'luxury',
    subcategory: '首饰',
    region: 'cn',
    sourceType: 'Official Site',
    listUrl: 'https://www.cartier.cn/zh-cn/collections/watches/',
    sourceLabel: '卡地亚中国官网·Tank Française 腕表',
    fetchMode: 'html',
    products: ['Tank Française', 'Tank Must', 'Tank Louis Cartier'],
    keywords: ['Cartier', 'Tank', '腕表', 'Française'],
    imageStrategy: 'product-page',
    cadence: 'daily',
    enabled: true,
  },
  {
    brand: 'Dior',
    category: 'luxury',
    subcategory: '包袋',
    region: 'cn',
    sourceType: 'Official Site',
    listUrl: 'https://www.dior.cn/zh_cn/fashion/womens-fashion/bags/',
    sourceLabel: 'Dior 中国官网女士包袋',
    fetchMode: 'html',
    products: ['Lady D-Joy 手袋', 'Book Tote 手袋', 'Dioramour 迷你 Book Tote'],
    keywords: ['Dior', '手袋', 'Lady D-Joy', 'Book Tote'],
    imageStrategy: 'product-page',
    cadence: 'wed-sun-twice',
    enabled: true,
  },
  {
    brand: 'Dior',
    category: 'luxury',
    subcategory: '首饰',
    region: 'cn',
    sourceType: 'Official Site',
    listUrl: 'https://www.dior.cn/zh_cn/fashion/jewelry-timepieces/rose-des-vents-home',
    sourceLabel: 'Dior 中国官网 Rose des Vents 首饰系列页',
    fetchMode: 'html',
    products: ['Rose des Vents 首饰', 'Oui 戒指', 'GEM DIOR 系列'],
    keywords: ['Dior', '首饰', 'Rose des Vents', 'GEM DIOR'],
    imageStrategy: 'product-page',
    cadence: 'wed-sun-twice',
    enabled: true,
  },
  {
    brand: 'Dior Beauty',
    category: 'beauty',
    subcategory: '彩妆',
    region: 'cn',
    sourceType: 'Official News',
    listUrl: 'https://www.dior.cn/zh_cn/beauty/whats-new-skincare-makeup-fragrance',
    sourceLabel: "Dior Beauty 中国官网·新品上市页",
    fetchMode: 'html',
    products: ['Dior Forever', 'Dior Addict', 'Lip Glow Oil'],
    keywords: ['new', 'forever', 'addict', 'lip'],
    imageStrategy: 'product-page',
    cadence: 'wed-sun-twice',
    enabled: true,
  },
  {
    brand: 'Dior Beauty',
    category: 'beauty',
    subcategory: '香水',
    region: 'cn',
    sourceType: 'Official Site',
    listUrl: 'https://www.dior.cn/zh_cn/beauty/fragrance/womens_fragrance/miss-dior',
    sourceLabel: 'Dior Beauty Miss Dior 系列页',
    fetchMode: 'html',
    products: ['Miss Dior 淡香精', 'J’adore', 'Sauvage'],
    keywords: ['Dior Beauty', '香水', 'Miss Dior', 'J’adore'],
    imageStrategy: 'product-page',
    cadence: 'wed-sun-twice',
    enabled: true,
  },
  {
    brand: 'Dior Beauty',
    category: 'beauty',
    subcategory: '香水',
    region: 'cn',
    sourceType: 'Official Site',
    listUrl: 'https://www.dior.cn/zh_cn/beauty/fragrance/womens_fragrance/jadore',
    sourceLabel: 'Dior Beauty J’adore 系列页',
    fetchMode: 'html',
    products: ['J’adore 淡香精', "J’adore Parfum d'eau", 'J’adore 身体乳'],
    keywords: ['Dior Beauty', '香水', 'J’adore', '花束香调'],
    imageStrategy: 'product-page',
    cadence: 'wed-sun-twice',
    enabled: true,
  },
  {
    brand: 'Dior Beauty',
    category: 'beauty',
    subcategory: '香水',
    region: 'cn',
    sourceType: 'Official Site',
    listUrl: 'https://www.dior.cn/zh_cn/beauty/products/y0685240-sauvage-eau-de-toilette',
    sourceLabel: 'Dior Beauty Sauvage 产品页',
    fetchMode: 'html',
    products: ['Sauvage 淡香水', 'Sauvage Eau Forte', 'Sauvage 须后润肤露'],
    keywords: ['Dior Beauty', '香水', 'Sauvage', '男士香氛'],
    imageStrategy: 'product-page',
    cadence: 'wed-sun-twice',
    enabled: true,
  },
  {
    brand: 'CHANEL Beauty',
    category: 'beauty',
    subcategory: '香水',
    region: 'cn',
    sourceType: 'Official Site',
    listUrl: 'https://www.chanel.cn/cn/fragrance/',
    sourceLabel: 'CHANEL Beauty 中国官网香氛',
    fetchMode: 'html',
    products: ['N°5', 'CHANCE EAU SPLENDIDE', 'COCO MADEMOISELLE'],
    keywords: ['CHANEL Beauty', '香水', 'N°5', 'CHANCE'],
    imageStrategy: 'product-page',
    cadence: 'wed-sun-twice',
    enabled: true,
  },
  {
    brand: 'CHANEL Beauty',
    category: 'beauty',
    subcategory: '香水',
    region: 'cn',
    sourceType: 'Official Site',
    listUrl: 'https://www.chanel.cn/cn/fragrance/p/125530/n5-eau-de-parfum-spray/',
    sourceLabel: 'CHANEL Beauty N°5 产品页',
    fetchMode: 'html',
    products: ['N°5 香奈儿五号香水（经典）', "N°5 L'EAU 香奈儿五号之水", 'N°5 香奈儿五号香水随行手袋装'],
    keywords: ['CHANEL Beauty', '香水', 'N°5', '五号香水'],
    imageStrategy: 'product-page',
    cadence: 'wed-sun-twice',
    enabled: true,
  },
  {
    brand: 'CHANEL Beauty',
    category: 'beauty',
    subcategory: '香水',
    region: 'cn',
    sourceType: 'Official Site',
    listUrl: 'https://www.chanel.cn/cn/fragrance/p/136210/chance-eau-splendide-eau-de-parfum-spray/',
    sourceLabel: 'CHANEL Beauty Chance 系列产品页',
    fetchMode: 'html',
    products: ['CHANCE EAU SPLENDIDE 香奈儿邂逅梦幻香水', 'CHANCE EAU TENDRE 香奈儿邂逅柔情香水', 'Chance Eau Splendide 润体乳'],
    keywords: ['CHANEL Beauty', '香水', 'Chance', '邂逅'],
    imageStrategy: 'product-page',
    cadence: 'wed-sun-twice',
    enabled: true,
  },
  {
    brand: 'Hermès Beauty',
    category: 'beauty',
    subcategory: '香水',
    region: 'cn',
    sourceType: 'Official Site',
    listUrl: 'https://www.hermes.cn/cn/en/category/fragrances/',
    sourceLabel: 'Hermès Beauty 香氛',
    fetchMode: 'html',
    products: ['大地馥郁香根草香型香水', '尼罗河花园香水', '李先生的花园香水'],
    keywords: ['Hermès Beauty', '香水', '花园系列', '大地'],
    imageStrategy: 'product-page',
    cadence: 'wed-sun-twice',
    enabled: true,
  },
  {
    brand: 'Hermès Beauty',
    category: 'beauty',
    subcategory: '香水',
    region: 'cn',
    sourceType: 'Official Site',
    listUrl: 'https://www.hermes.cn/cn/en/category/fragrances/men/',
    sourceLabel: 'Hermès Beauty 男士香水',
    fetchMode: 'html',
    products: ['爱马仕大地馥郁香根草香型香水', 'Terre d’Hermès 淡香水', 'Terre d’Hermès 须后润肤露'],
    keywords: ['Hermès Beauty', '香水', 'Terre d’Hermès', '大地'],
    imageStrategy: 'product-page',
    cadence: 'wed-sun-twice',
    enabled: true,
  },
  {
    brand: 'Hermès Beauty',
    category: 'beauty',
    subcategory: '香水',
    region: 'cn',
    sourceType: 'Official Site',
    listUrl: 'https://www.hermes.cn/cn/en/category/fragrances/women/',
    sourceLabel: 'Hermès Beauty 女士香水',
    fetchMode: 'html',
    products: ['爱马仕丝意荔韵淡香精', 'Twilly d’Hermès 淡香精', 'Twilly d’Hermès 润体乳'],
    keywords: ['Hermès Beauty', '香水', 'Twilly', '丝意'],
    imageStrategy: 'product-page',
    cadence: 'wed-sun-twice',
    enabled: true,
  },
  {
    brand: 'Hermès Beauty',
    category: 'beauty',
    subcategory: '香水',
    region: 'cn',
    sourceType: 'Official Site',
    listUrl: 'https://www.hermes.cn/cn/en/category/fragrances/',
    sourceLabel: 'Hermès Beauty 花园系列',
    fetchMode: 'html',
    products: ['Un Jardin Sous La Mer 海底花园香水', 'Un Jardin Sur Le Toit 屋顶花园香水', 'Un Jardin Sur La Lagune 泻湖花园香水'],
    keywords: ['Hermès Beauty', '香水', '花园', 'Jardin'],
    imageStrategy: 'product-page',
    cadence: 'wed-sun-twice',
    enabled: true,
  },
  {
    brand: 'Hermès Beauty',
    category: 'beauty',
    subcategory: '香水',
    region: 'cn',
    sourceType: 'Official Site',
    listUrl: 'https://www.hermes.cn/cn/en/category/fragrances/',
    sourceLabel: 'Hermès Beauty 闻香珍藏系列',
    fetchMode: 'html',
    products: ['Osmanthe Yunnan 云南丹桂香水', 'Cedre Sambac 雪松茉莉香水', 'Poivre Samarcande 撒马尔罕胡椒香水', 'Violette Volynka 紫罗兰皮革香水'],
    keywords: ['Hermès Beauty', '香水', '闻香珍藏', 'Hermessence'],
    imageStrategy: 'product-page',
    cadence: 'wed-sun-twice',
    enabled: true,
  },
  {
    brand: 'Hermès Beauty',
    category: 'beauty',
    subcategory: '香水',
    region: 'cn',
    sourceType: 'Official Site',
    listUrl: 'https://www.hermes.cn/cn/en/category/fragrances/',
    sourceLabel: 'Hermès Beauty 男士与中性香水',
    fetchMode: 'html',
    products: ['H24 Herbes Vives 淡香精', 'Barenia 淡香精', "Eau des Merveilles 橘彩星光香水", "Eau de Citron Noir 黑柠檬香水"],
    keywords: ['Hermès Beauty', '香水', 'H24', 'Barenia', '橘彩星光'],
    imageStrategy: 'product-page',
    cadence: 'wed-sun-twice',
    enabled: true,
  },
  {
    brand: 'SHISEIDO',
    category: 'beauty',
    subcategory: '护肤',
    region: 'cn',
    sourceType: 'Official Site',
    listUrl: 'https://www.shiseido.com.cn/',
    sourceLabel: '资生堂中国官网',
    fetchMode: 'browser',
    products: ['红腰子精华', '蓝胖子防晒', '悦薇系列'],
    keywords: ['红腰子', '防晒', '精华', '新品'],
    imageStrategy: 'homepage-module',
    cadence: 'wed-sun-twice',
    enabled: true,
  },
  {
    brand: 'SHISEIDO',
    category: 'beauty',
    subcategory: '护肤',
    region: 'cn',
    sourceType: 'Official Site',
    listUrl: 'https://www.shiseido.com.cn/benefiance-serum-0086.html',
    sourceLabel: '资生堂中国官网·「爆珠」精华',
    fetchMode: 'browser',
    products: ['百优「爆珠」精华', '百优系列', '悦薇珀翡系列'],
    keywords: ['百优', '爆珠', '精华', '抗老'],
    imageStrategy: 'product-page',
    cadence: 'wed-sun-twice',
    enabled: true,
  },
  {
    brand: 'SHISEIDO',
    category: 'beauty',
    subcategory: '护肤',
    region: 'cn',
    sourceType: 'Official Site',
    listUrl: 'https://www.shiseido.com.cn/vpn-liftdefine-radiance-serum-s16871.html',
    sourceLabel: '资生堂中国官网·悦薇「抗糖」精华',
    fetchMode: 'browser',
    products: ['悦薇「抗糖」精华', '悦薇珀翡', '抗糖抗老'],
    keywords: ['悦薇', '抗糖', '精华'],
    imageStrategy: 'product-page',
    cadence: 'wed-sun-twice',
    enabled: true,
  },
  {
    brand: 'SHISEIDO',
    category: 'beauty',
    subcategory: '护肤',
    region: 'cn',
    sourceType: 'Official Site',
    listUrl: 'https://www.shiseido.com.cn/clarify-cleanse-foam-0004.html',
    sourceLabel: '资生堂中国官网·肌源焕采洁面膏',
    fetchMode: 'browser',
    products: ['肌源焕采洁面膏', 'WASO', '保湿洁面'],
    keywords: ['洁面', '肌源焕采', '保湿'],
    imageStrategy: 'product-page',
    cadence: 'wed-sun-twice',
    enabled: true,
  },
  {
    brand: 'SHISEIDO',
    category: 'beauty',
    subcategory: '护肤',
    region: 'cn',
    sourceType: 'Official Site',
    listUrl: 'https://www.shiseido.com.cn/%E3%80%8C%E7%8E%89%E7%90%89%E7%92%83%E3%80%8D%E7%94%9F%E6%9C%BA%E7%B2%BE%E5%8D%8E-2026030604.html',
    sourceLabel: '资生堂中国官网·时光琉璃「玉琉璃」生机精华',
    fetchMode: 'browser',
    products: ['「玉琉璃」生机精华', '时光琉璃系列', 'Future Solution LX'],
    keywords: ['玉琉璃', '时光琉璃', '生机精华', '抗老'],
    imageStrategy: 'product-page',
    cadence: 'daily',
    enabled: true,
  },
  {
    brand: 'SHISEIDO',
    category: 'beauty',
    subcategory: '护肤',
    region: 'cn',
    sourceType: 'Official Site',
    listUrl: 'https://www.shiseido.com.cn/%E3%80%8C%E7%8E%89%E7%90%89%E7%92%83%E3%80%8D%E7%94%9F%E6%9C%BA%E9%9D%A2%E9%9C%9C-2026030605.html',
    sourceLabel: '资生堂中国官网·时光琉璃「玉琉璃」生机面霜',
    fetchMode: 'browser',
    products: ['「玉琉璃」生机面霜', '时光琉璃系列'],
    keywords: ['玉琉璃', '时光琉璃', '生机面霜', '抗老'],
    imageStrategy: 'product-page',
    cadence: 'daily',
    enabled: true,
  },
  {
    brand: 'SHISEIDO',
    category: 'beauty',
    subcategory: '护肤',
    region: 'cn',
    sourceType: 'Official Site',
    listUrl: 'https://www.shiseido.com.cn/%E6%82%A6%E8%96%87%E3%80%8C%E8%83%B6%E5%8E%9F%E7%82%AE%E3%80%8DPRO%E9%9D%A2%E9%9C%9C-2026030601.html',
    sourceLabel: '资生堂中国官网·悦薇「胶原炮」PRO面霜',
    fetchMode: 'browser',
    products: ['悦薇「胶原炮」PRO面霜', '悦薇珀翡系列', 'Vital Perfection'],
    keywords: ['悦薇', '胶原炮', '面霜', '抗老'],
    imageStrategy: 'product-page',
    cadence: 'daily',
    enabled: true,
  },
  {
    brand: 'SHISEIDO',
    category: 'beauty',
    subcategory: '护肤',
    region: 'cn',
    sourceType: 'Official Site',
    listUrl: 'https://www.shiseido.com.cn/%E3%80%8C%E7%BA%A2%E8%85%B0%E5%AD%90%E3%80%8D%E7%B2%BE%E5%8D%8E%E7%9C%BC%E9%9C%9C-s18866eye.html',
    sourceLabel: '资生堂中国官网·「红腰子」精华眼霜',
    fetchMode: 'browser',
    products: ['「红腰子」精华眼霜', '红妍肌活系列'],
    keywords: ['红腰子', '眼霜', '精华'],
    imageStrategy: 'product-page',
    cadence: 'daily',
    enabled: true,
  },
  {
    brand: 'SHISEIDO',
    category: 'beauty',
    subcategory: '护肤',
    region: 'cn',
    sourceType: 'Official Site',
    listUrl: 'https://www.shiseido.com.cn/%E5%BE%A1%E7%99%BD%E6%A8%B1%E8%8A%B1%E7%93%B6-s18305.html',
    sourceLabel: '资生堂中国官网·御白樱花瓶',
    fetchMode: 'browser',
    products: ['御白樱花瓶', 'White Lucent', '美白精华'],
    keywords: ['御白', '樱花瓶', '美白', '精华'],
    imageStrategy: 'product-page',
    cadence: 'daily',
    enabled: true,
  },
  {
    brand: 'SHISEIDO',
    category: 'beauty',
    subcategory: '防晒',
    region: 'cn',
    sourceType: 'Official Site',
    listUrl: 'https://www.shiseido.com.cn/%E3%80%8C%E7%B2%89%E8%83%96%E5%AD%90%E3%80%8D%E9%98%B2%E6%99%92-s18303.html',
    sourceLabel: '资生堂中国官网·「粉胖子」防晒',
    fetchMode: 'browser',
    products: ['「粉胖子」防晒', '防晒', '蓝胖子'],
    keywords: ['粉胖子', '防晒', 'Urban Environment'],
    imageStrategy: 'product-page',
    cadence: 'daily',
    enabled: true,
  },
  {
    brand: 'Prada Beauty',
    category: 'beauty',
    subcategory: '香水',
    region: 'cn',
    sourceType: 'Official Site',
    listUrl: 'https://www.prada.cn/cn/zh/perfumes-and-beauty/perfumes/c/10562CN',
    sourceLabel: 'Prada Beauty 中国官网·香水',
    fetchMode: 'html',
    products: ['Paradoxe Radical Essence', 'Prada Paradoxe'],
    keywords: ['Prada', 'Paradoxe', '香水', 'Radical'],
    imageStrategy: 'product-page',
    cadence: 'daily',
    enabled: true,
  },
  {
    brand: 'Prada Beauty',
    category: 'beauty',
    subcategory: '香水',
    region: 'cn',
    sourceType: 'Official Site',
    listUrl: 'https://www.prada.cn/cn/zh/perfumes-and-beauty/perfumes/c/10562CN',
    sourceLabel: 'Prada Beauty 中国官网·香水',
    fetchMode: 'html',
    products: ['Luna Rossa Ocean', 'Prada Luna Rossa'],
    keywords: ['Prada', 'Luna Rossa', '香水', 'Ocean'],
    imageStrategy: 'product-page',
    cadence: 'daily',
    enabled: true,
  },
  {
    brand: 'Prada Beauty',
    category: 'beauty',
    subcategory: '彩妆',
    region: 'cn',
    sourceType: 'Official Site',
    listUrl: 'https://www.prada.cn/cn/zh/perfumes-and-beauty/beauty/c/10565CN',
    sourceLabel: 'Prada Beauty 中国官网·彩妆',
    fetchMode: 'html',
    products: ['Prada Reveal', '柔雾多用膏', '粉底'],
    keywords: ['Prada', 'Reveal', '彩妆', '粉底'],
    imageStrategy: 'product-page',
    cadence: 'daily',
    enabled: true,
  },
  {
    brand: 'Prada Beauty',
    category: 'beauty',
    subcategory: '彩妆',
    region: 'cn',
    sourceType: 'Official Site',
    listUrl: 'https://www.prada.cn/cn/zh/perfumes-and-beauty/beauty/c/10565CN',
    sourceLabel: 'Prada Beauty 中国官网·彩妆',
    fetchMode: 'html',
    products: ['Prada Monochrome', '哑光唇膏', '唇膏'],
    keywords: ['Prada', 'Monochrome', '唇膏', '彩妆'],
    imageStrategy: 'product-page',
    cadence: 'daily',
    enabled: true,
  },
  {
    brand: 'Prada Beauty',
    category: 'beauty',
    subcategory: '香水',
    region: 'cn',
    sourceType: 'Official Site',
    listUrl: 'https://www.prada.cn/cn/zh/perfumes-and-beauty/beauty/c/10565CN',
    sourceLabel: 'Prada Beauty 中国官网美妆页',
    fetchMode: 'browser',
    products: ['Prada 美妆', '护肤', '彩妆'],
    keywords: ['Prada', 'beauty', '护肤', '彩妆'],
    imageStrategy: 'homepage-module',
    cadence: 'daily',
    enabled: true,
  },
  {
    brand: 'Prada Beauty',
    category: 'beauty',
    subcategory: '香水',
    region: 'cn',
    sourceType: 'Official Site',
    listUrl: 'https://www.prada.cn/cn/zh/perfumes-and-beauty/perfumes/c/10562CN',
    sourceLabel: 'Prada Beauty 中国官网香水页',
    fetchMode: 'browser',
    products: ['Prada 香水', 'Paradoxe', 'Luna Rossa', 'Candy'],
    keywords: ['Prada', '香水', 'Paradoxe', 'Luna Rossa'],
    imageStrategy: 'homepage-module',
    cadence: 'daily',
    enabled: true,
  },
  {
    brand: 'Samsung',
    category: 'digital',
    subcategory: '手机',
    region: 'cn',
    sourceType: 'Official Site',
    listUrl: 'https://www.samsung.com.cn/smartphones/',
    sourceLabel: '三星中国官网智能手机',
    fetchMode: 'html',
    products: ['Galaxy S26', 'Galaxy S26+', 'Galaxy S26 Ultra'],
    keywords: ['Samsung', 'Galaxy', '手机', 'S26'],
    imageStrategy: 'homepage-module',
    cadence: 'wed-sun-twice',
    enabled: true,
  },
  {
    brand: 'Samsung',
    category: 'digital',
    subcategory: '平板',
    region: 'cn',
    sourceType: 'Official Site',
    listUrl: 'https://www.samsung.com.cn/tablets/',
    sourceLabel: '三星中国官网平板',
    fetchMode: 'html',
    products: ['Galaxy Tab S11 Ultra', 'Galaxy Tab S11', 'S Pen'],
    keywords: ['Samsung', 'Galaxy Tab', '平板', 'S11'],
    imageStrategy: 'homepage-module',
    cadence: 'wed-sun-twice',
    enabled: true,
  },
  {
    brand: 'Samsung',
    category: 'digital',
    subcategory: '配件',
    region: 'cn',
    sourceType: 'Official Site',
    listUrl: 'https://www.samsung.com.cn/audio-sound/',
    sourceLabel: '三星中国官网音频配件',
    fetchMode: 'html',
    products: ['Galaxy Buds', 'Galaxy AI', 'Galaxy 生态配件'],
    keywords: ['Samsung', 'Galaxy Buds', '配件', '生态'],
    imageStrategy: 'homepage-module',
    cadence: 'wed-sun-twice',
    enabled: true,
  },
  {
    brand: 'Adidas',
    category: 'sports',
    subcategory: '足球',
    region: 'cn',
    sourceType: 'Official Site',
    // 2026-08-29: F50 足球鞋 campaign 已过时；adidas plp 列表页为 JS 渲染（curl 拿不到产品数据），
    // 无法简单改 listUrl 修复（会产出通用 title + 空图）。暂禁用，后续需 browser 渲染方案再恢复。
    listUrl: 'https://www.adidas.com.cn/pdp?articleId=JQ0952',
    sourceLabel: 'adidas 中国官网',
    fetchMode: 'html',
    products: ['F50 Messi Elite FG', 'F50 League TF', 'F50 League AG'],
    keywords: ['F50', 'Messi', '足球鞋', 'Elite FG'],
    imageStrategy: 'gallery-image',
    cadence: 'wed-sun-twice',
    enabled: false,
  },
  {
    brand: 'Adidas',
    category: 'sports',
    subcategory: '篮球',
    region: 'cn',
    sourceType: 'Official Site',
    listUrl: 'https://www.adidas.com.cn/',
    sourceLabel: 'adidas 中国大陆官网首页',
    fetchMode: 'html',
    products: ['ANTHONY EDWARDS 2', '爱德华兹2代篮球运动鞋', '极速蓝调'],
    keywords: ['聚焦热点', '极速蓝调', '篮球', 'Anthony Edwards 2'],
    imageStrategy: 'gallery-image',
    cadence: 'wed-sun-twice',
    enabled: true,
  },
  {
    brand: 'Adidas',
    category: 'sports',
    subcategory: '户外',
    region: 'cn',
    sourceType: 'Official Site',
    listUrl: 'https://www.adidas.com.cn/',
    sourceLabel: 'adidas 中国大陆官网首页',
    fetchMode: 'html',
    products: ['TERREX FH LT SANDAL', '自由人系列', '城市机能风'],
    keywords: ['聚焦热点', '自由人系列', '城市机能风', '户外'],
    imageStrategy: 'gallery-image',
    cadence: 'wed-sun-twice',
    enabled: true,
  },
  {
    brand: 'Adidas',
    category: 'sports',
    subcategory: '运动休闲',
    region: 'cn',
    sourceType: 'Official Site',
    listUrl: 'https://www.adidas.com.cn/',
    sourceLabel: 'adidas 中国大陆官网首页',
    fetchMode: 'html',
    products: ['静奢甄选', '东方柔雅风', '三条纹舞动系列'],
    keywords: ['新品推荐', '静奢甄选', '东方柔雅风', '三条纹舞动系列'],
    imageStrategy: 'gallery-image',
    cadence: 'wed-sun-twice',
    enabled: true,
  },
  {
    brand: 'Wilson',
    category: 'sports',
    subcategory: '网球',
    region: 'cn',
    sourceType: 'Official News',
    listUrl: 'https://www.wilson.com/en-us/tennis',
    sourceLabel: 'Wilson Tennis',
    fetchMode: 'browser',
    products: ['Rush Pro 4.5', 'Rush Pro 4.0', '4D Support Chassis 2.0'],
    keywords: ['Rush Pro 4.5', 'tennis shoe', 'new'],
    imageStrategy: 'page-screenshot',
    cadence: 'wed-sun-twice',
    enabled: true,
  },
  {
    brand: 'Chanel',
    category: 'luxury',
    subcategory: '眼镜',
    region: 'cn',
    sourceType: 'New Arrivals',
    listUrl: 'https://www.chanel.cn/cn/eyewear/sunglasses/c/2x3x1x3/new-this-season/',
    sourceLabel: '香奈儿中国官网眼镜当季新款',
    fetchMode: 'browser',
    products: ['猫眼形太阳眼镜', 'PANTOS太阳眼镜', '矩形框太阳眼镜', '椭圆形框太阳眼镜', '飞行员太阳眼镜'],
    keywords: ['太阳眼镜', '当季新款', 'new this season', 'sunglasses'],
    imageStrategy: 'product-page',
    cadence: 'wed-sun-twice',
    enabled: true,
  },
  {
    brand: 'Chanel',
    category: 'luxury',
    subcategory: '手袋',
    region: 'cn',
    sourceType: 'New Arrivals',
    listUrl: 'https://www.chanel.cn/cn/fashion/handbags/c/1x1x1/',
    sourceLabel: '香奈儿中国官网手袋全系列',
    fetchMode: 'browser',
    products: ['口盖包', 'CHANEL 25手袋', '流浪包', '水桶包', '购物包', '保龄球包'],
    keywords: ['手袋', '口盖包', 'CHANEL 25', '保龄球包', 'handbag'],
    imageStrategy: 'product-page',
    cadence: 'wed-sun-twice',
    enabled: true,
  },
  {
    brand: 'Chanel',
    category: 'luxury',
    subcategory: '成衣',
    region: 'cn',
    sourceType: 'New Arrivals',
    listUrl: 'https://www.chanel.cn/cn/fashion/',
    sourceLabel: '香奈儿中国官网时装系列',
    fetchMode: 'browser',
    products: ['2026秋冬预告系列', '2026高级手工坊系列', 'CHANEL COCO BEACH', '早春度假系列'],
    keywords: ['时装', '成衣', '系列', 'collection', 'new'],
    imageStrategy: 'product-page',
    cadence: 'wed-sun-twice',
    enabled: true,
  },
  {
    brand: 'Chanel',
    category: 'luxury',
    subcategory: '饰品',
    region: 'cn',
    sourceType: 'New Arrivals',
    listUrl: 'https://www.chanel.cn/cn/fashion/costume-jewelry/c/1x1x3/',
    sourceLabel: '香奈儿中国官网服饰珠宝',
    fetchMode: 'browser',
    products: ['耳环', '项链', '手链', '胸针', '戒指'],
    keywords: ['服饰珠宝', '耳环', '项链', 'costume jewelry'],
    imageStrategy: 'product-page',
    cadence: 'wed-sun-twice',
    enabled: true,
  },
  {
    brand: 'Chanel',
    category: 'luxury',
    subcategory: '腕表',
    region: 'cn',
    sourceType: 'Official Site',
    listUrl: 'https://www.chanel.cn/cn/watches/',
    sourceLabel: '香奈儿中国官网腕表频道',
    fetchMode: 'html',
    products: ['J12 BLEU蓝宝石腕表', '38毫米', 'Caliber 12.1机芯'],
    keywords: ['腕表', 'J12', 'Première', 'CHANEL watches'],
    imageStrategy: 'product-page',
    cadence: 'wed-sun-twice',
    enabled: false,
  },
  {
    brand: 'Chanel',
    category: 'luxury',
    subcategory: '手袋',
    region: 'cn',
    sourceType: 'New Arrivals',
    listUrl: 'https://www.chanel.cn/cn/fashion/handbags/chanel-25/',
    sourceLabel: 'Chanel 25 手袋',
    fetchMode: 'html',
    products: ['CHANEL 25迷你手袋', 'CHANEL 25小号手袋', '羊皮革', '斜纹软呢', '丹宁'],
    keywords: ['手袋', 'CHANEL 25', '迷你', '小号', 'new'],
    imageStrategy: 'product-page',
    cadence: 'wed-sun-twice',
    enabled: false,
  },
  {
    brand: 'Chanel',
    category: 'luxury',
    subcategory: '手袋',
    region: 'cn',
    sourceType: 'Official Site',
    listUrl: 'https://www.chanel.cn/cn/fashion/handbags/classic/',
    sourceLabel: 'Chanel 经典手袋',
    fetchMode: 'html',
    products: ['Classic手袋', '2.55手袋', 'CHANEL 22手袋', 'Boy Chanel手袋'],
    keywords: ['手袋', 'Classic', '2.55', 'CHANEL 22', 'Boy Chanel'],
    imageStrategy: 'product-page',
    cadence: 'wed-sun-twice',
    enabled: false,
  },
  {
    brand: 'Chanel',
    category: 'luxury',
    subcategory: '成衣',
    region: 'cn',
    sourceType: 'New Arrivals',
    listUrl: 'https://www.chanel.cn/cn/fashion/collection/spring-summer-2026-products/',
    sourceLabel: 'Chanel 2026春夏系列',
    fetchMode: 'html',
    products: ['斜纹软呢外套', '真丝衬衫', '连衣裙', '半身裙'],
    keywords: ['春夏', '2026', '成衣', 'collection', 'spring-summer'],
    imageStrategy: 'product-page',
    cadence: 'wed-sun-twice',
    enabled: false,
  },
  {
    brand: 'Chanel',
    category: 'luxury',
    subcategory: '成衣',
    region: 'cn',
    sourceType: 'Official Site',
    listUrl: 'https://www.chanel.cn/cn/fashion/collection/metiers-art-2026/',
    sourceLabel: 'Chanel 2026高级手工坊',
    fetchMode: 'html',
    products: ['高级手工坊', 'Métiers', '刺绣', '羽毛', 'Lesage'],
    keywords: ['高级手工坊', 'Métiers', 'Paris', '工坊', '2026'],
    imageStrategy: 'product-page',
    cadence: 'wed-sun-twice',
    enabled: false,
  },
  {
    brand: 'Chanel',
    category: 'luxury',
    subcategory: '成衣',
    region: 'cn',
    sourceType: 'Official Site',
    listUrl: 'https://www.chanel.cn/cn/fashion/collection/chanel-coco-beach-2026-campaign/',
    sourceLabel: 'Chanel COCO BEACH 2026',
    fetchMode: 'html',
    products: ['贝壳蕾丝', '真丝连衣裙', 'jersey泳装', '条纹针织衫', '航海风珠宝'],
    keywords: ['COCO BEACH', '2026', '夏日', 'beach', '度假'],
    imageStrategy: 'product-page',
    cadence: 'wed-sun-twice',
    enabled: false,
  },
  {
    brand: 'Chanel',
    category: 'luxury',
    subcategory: '眼镜',
    region: 'cn',
    sourceType: 'Official Site',
    listUrl: 'https://www.chanel.cn/cn/eyewear/2026-campaign/',
    sourceLabel: 'Chanel 眼镜2026春夏',
    fetchMode: 'html',
    products: ['太阳眼镜', '光学眼镜', '蝴蝶形', '猫眼形', '双C标志'],
    keywords: ['眼镜', 'eyewear', '2026', '春夏', '太阳镜'],
    imageStrategy: 'product-page',
    cadence: 'wed-sun-twice',
    enabled: false,
  },
  {
    brand: 'Chanel',
    category: 'luxury',
    subcategory: '成衣',
    region: 'cn',
    sourceType: 'Official Site',
    listUrl: 'https://www.chanel.cn/cn/fashion/collection/fall-winter-2026/',
    sourceLabel: 'Chanel 2026秋冬发布会',
    fetchMode: 'html',
    products: ['粗花呢', '皮革', '长外套', '层叠设计', '秋冬'],
    keywords: ['秋冬', '2026', 'fall-winter', 'runway', '发布会'],
    imageStrategy: 'product-page',
    cadence: 'wed-sun-twice',
    enabled: false,
  },
  {
    brand: 'Chanel',
    category: 'luxury',
    subcategory: '成衣',
    region: 'cn',
    sourceType: 'Official Site',
    listUrl: 'https://www.chanel.cn/cn/fashion/collection/cruise-2026-27/',
    sourceLabel: 'Chanel 2026/27早春度假',
    fetchMode: 'html',
    products: ['早春度假', 'Cruise', '2026/27', '航海', '轻盈面料'],
    keywords: ['早春度假', 'Cruise', '2026/27', '度假', '海洋'],
    imageStrategy: 'product-page',
    cadence: 'wed-sun-twice',
    enabled: false,
  },
  {
    brand: 'Chanel',
    category: 'luxury',
    subcategory: '珠宝',
    region: 'cn',
    sourceType: 'Official Site',
    listUrl: 'https://www.chanel.cn/cn/fine-jewelry/',
    sourceLabel: 'Chanel 高级珠宝',
    fetchMode: 'html',
    products: ['Coco Crush', 'Camélia', 'Comète', 'Plume', 'Ruban'],
    keywords: ['珠宝', 'fine jewelry', 'Coco Crush', 'Camélia', '钻石'],
    imageStrategy: 'product-page',
    cadence: 'wed-sun-twice',
    enabled: false,
  },
  {
    brand: 'Chanel',
    category: 'luxury',
    subcategory: '手袋',
    region: 'cn',
    sourceType: 'Official Site',
    listUrl: 'https://www.chanel.cn/cn/fashion/handbags/chanel-22/',
    sourceLabel: 'Chanel 22 手袋',
    fetchMode: 'html',
    products: ['CHANEL 22手袋', '大号', '小号', '迷你'],
    keywords: ['CHANEL 22', '手袋', '经典', 'new'],
    imageStrategy: 'product-page',
    cadence: 'daily',
    enabled: false,
  },
  {
    brand: 'Chanel',
    category: 'luxury',
    subcategory: '手袋',
    region: 'cn',
    sourceType: 'Official Site',
    listUrl: 'https://www.chanel.cn/cn/fashion/handbags/boy-chanel/',
    sourceLabel: 'Boy Chanel 手袋',
    fetchMode: 'html',
    products: ['Boy Chanel手袋', '小号', '中号', '口盖包'],
    keywords: ['Boy Chanel', '手袋', '口盖包', 'new'],
    imageStrategy: 'product-page',
    cadence: 'daily',
    enabled: false,
  },
  {
    brand: 'Chanel',
    category: 'luxury',
    subcategory: '手袋',
    region: 'cn',
    sourceType: 'Official Site',
    listUrl: 'https://www.chanel.cn/cn/fashion/handbags/chanel-19/',
    sourceLabel: 'Chanel 19 手袋',
    fetchMode: 'html',
    products: ['CHANEL 19手袋', '大号', '小号', '斜纹软呢'],
    keywords: ['CHANEL 19', '手袋', '斜纹软呢', 'new'],
    imageStrategy: 'product-page',
    cadence: 'daily',
    enabled: false,
  },
  {
    brand: 'Chanel',
    category: 'luxury',
    subcategory: '腕表',
    region: 'cn',
    sourceType: 'Official Site',
    listUrl: 'https://www.chanel.cn/cn/watches/p/H11059/j12-superleggera-caliber-12-1-42-mm-watch/',
    sourceLabel: 'J12 Superleggera 腕表',
    fetchMode: 'html',
    products: ['J12 Superleggera', 'Caliber 12.1', '42毫米', '陶瓷'],
    keywords: ['J12', 'Superleggera', '腕表', '陶瓷', '42mm'],
    imageStrategy: 'product-page',
    cadence: 'daily',
    enabled: false,
  },
  {
    brand: 'Chanel',
    category: 'luxury',
    subcategory: '珠宝',
    region: 'cn',
    sourceType: 'Official Site',
    listUrl: 'https://www.chanel.cn/cn/fine-jewelry/coco-crush/',
    sourceLabel: 'Coco Crush 系列',
    fetchMode: 'html',
    products: ['Coco Crush戒指', 'Coco Crush手镯', 'Coco Crush项链', 'Coco Crush耳环'],
    keywords: ['Coco Crush', '戒指', '手镯', '项链', '耳环'],
    imageStrategy: 'product-page',
    cadence: 'daily',
    enabled: false,
  },
  {
    brand: 'Chanel',
    category: 'luxury',
    subcategory: '珠宝',
    region: 'cn',
    sourceType: 'Official Site',
    listUrl: 'https://www.chanel.cn/cn/fine-jewelry/new-fine-jewelry/c/3x3x26/',
    sourceLabel: 'Chanel 新品高级珠宝',
    fetchMode: 'html',
    products: ['高级珠宝', '钻石', '白金', '黄金'],
    keywords: ['珠宝', '高级珠宝', '新品', 'new', 'fine jewelry'],
    imageStrategy: 'product-page',
    cadence: 'daily',
    enabled: false,
  },
  {
    brand: 'Chanel',
    category: 'luxury',
    subcategory: '珠宝',
    region: 'cn',
    sourceType: 'Official Site',
    listUrl: 'https://www.chanel.cn/cn/fine-jewelry/18-place-vendome/',
    sourceLabel: 'Chanel 18 Place Vendôme',
    fetchMode: 'html',
    products: ['Place Vendôme', '钻石', '白金', '高级珠宝'],
    keywords: ['Place Vendôme', '高级珠宝', '钻石', '芳登广场'],
    imageStrategy: 'product-page',
    cadence: 'daily',
    enabled: false,
  },
  {
    brand: 'OMEGA',
    category: 'luxury',
    subcategory: '腕表',
    region: 'cn',
    sourceType: 'Official News',
    listUrl: 'https://www.omegawatches.cn/stories',
    sourceLabel: '欧米茄中国官网新闻资讯与故事',
    fetchMode: 'browser',
    products: ['星座系列', '海马系列', '超霸系列', '月球表'],
    keywords: ['欧米茄', 'OMEGA', '腕表', '新闻', 'stories'],
    imageStrategy: 'product-page',
    cadence: 'wed-sun-twice',
    enabled: true,
  },
  {
    brand: 'Van Cleef & Arpels',
    category: 'luxury',
    subcategory: '珠宝',
    region: 'cn',
    sourceType: 'Official News',
    listUrl: 'https://www.vancleefarpels.cn/cn/zh/news.html',
    sourceLabel: '梵克雅宝中国官网新闻中心',
    fetchMode: 'browser',
    products: ['Alhambra四叶幸运系列', 'Perlée系列', 'Frivole系列'],
    keywords: ['梵克雅宝', 'Van Cleef', '珠宝', '新闻', 'news'],
    imageStrategy: 'product-page',
    cadence: 'wed-sun-twice',
    enabled: true,
  },
  // ---- Boucheron 宝诗龙 ----
  {
    brand: 'Boucheron',
    category: 'luxury',
    subcategory: '珠宝',
    region: 'cn',
    sourceType: 'Official Site',
    listUrl: 'https://www.boucheron.cn/cn_zh/jewelry/jewelry-collection/quatre.html',
    sourceLabel: 'Boucheron Quatre系列',
    fetchMode: 'html',
    products: ['Quatre', '戒指', '手镯', '项链'],
    keywords: ['Quatre', '戒指', '手镯', '项链', 'Boucheron'],
    imageStrategy: 'product-page',
    cadence: 'daily',
    enabled: false,
  },
  {
    brand: 'Boucheron',
    category: 'luxury',
    subcategory: '珠宝',
    region: 'cn',
    sourceType: 'Official Site',
    listUrl: 'https://www.boucheron.cn/cn_zh/jewelry/jewelry-collection/serpent-boheme.html',
    sourceLabel: 'Boucheron Serpent Bohème系列',
    fetchMode: 'html',
    products: ['Serpent Bohème', '戒指', '吊坠', '耳饰'],
    keywords: ['Serpent', 'Bohème', '戒指', '吊坠'],
    imageStrategy: 'product-page',
    cadence: 'daily',
    enabled: true,
  },
  {
    brand: 'Boucheron',
    category: 'luxury',
    subcategory: '珠宝',
    region: 'cn',
    sourceType: 'Official Site',
    listUrl: 'https://www.boucheron.cn/cn_zh/jewelry/jewelry-collection/jack-de-boucheron.html',
    sourceLabel: 'Boucheron Jack de Boucheron系列',
    fetchMode: 'html',
    products: ['Jack de Boucheron', '手链', '戒指', '项链'],
    keywords: ['Jack', 'Boucheron', '手链', '戒指'],
    imageStrategy: 'product-page',
    cadence: 'daily',
    enabled: true,
  },
  {
    brand: 'Boucheron',
    category: 'luxury',
    subcategory: '珠宝',
    region: 'cn',
    sourceType: 'Official Site',
    listUrl: 'https://www.boucheron.cn/cn_zh/jewelry/jewelry-category/rings.html',
    sourceLabel: 'Boucheron 戒指',
    fetchMode: 'html',
    products: ['戒指', 'Quatre', 'Serpent', 'Jack'],
    keywords: ['戒指', 'ring', 'Quatre', 'Serpent'],
    imageStrategy: 'product-page',
    cadence: 'daily',
    enabled: true,
  },
  {
    brand: 'Boucheron',
    category: 'luxury',
    subcategory: '珠宝',
    region: 'cn',
    sourceType: 'Official Site',
    listUrl: 'https://www.boucheron.cn/cn_zh/jewelry/jewelry-category/necklaces-pendants.html',
    sourceLabel: 'Boucheron 吊坠项链',
    fetchMode: 'html',
    products: ['吊坠', '项链', 'Serpent', 'Quatre'],
    keywords: ['吊坠', '项链', 'necklace', 'pendant'],
    imageStrategy: 'product-page',
    cadence: 'daily',
    enabled: true,
  },
  {
    brand: 'Boucheron',
    category: 'luxury',
    subcategory: '珠宝',
    region: 'cn',
    sourceType: 'Official Site',
    listUrl: 'https://www.boucheron.cn/cn_zh/jewelry/jewelry-category/bracelets.html',
    sourceLabel: 'Boucheron 手镯',
    fetchMode: 'html',
    products: ['手镯', '手链', 'Quatre', 'Jack'],
    keywords: ['手镯', '手链', 'bracelet', 'Quatre'],
    imageStrategy: 'product-page',
    cadence: 'daily',
    enabled: true,
  },
  {
    brand: 'Boucheron',
    category: 'luxury',
    subcategory: '珠宝',
    region: 'cn',
    sourceType: 'Official Site',
    listUrl: 'https://www.boucheron.cn/cn_zh/jewelry/jewelry-category/earrings.html',
    sourceLabel: 'Boucheron 耳饰',
    fetchMode: 'html',
    products: ['耳饰', '耳环', 'Serpent', 'Quatre'],
    keywords: ['耳饰', '耳环', 'earring', 'Serpent'],
    imageStrategy: 'product-page',
    cadence: 'daily',
    enabled: true,
  },
  {
    brand: 'ASICS',
    category: 'sports',
    subcategory: '网球',
    region: 'cn',
    sourceType: 'Official Site',
    listUrl: 'https://www.asics.com.cn/',
    sourceLabel: 'ASICS 中国官网首页',
    fetchMode: 'html',
    products: ['GEL-RESOLUTION 8', 'GEL-RESOLUTION 8 L.E.', '网球鞋款'],
    keywords: ['网球', 'GEL-RESOLUTION', 'ASICS', '鞋款'],
    imageStrategy: 'product-page',
    cadence: 'wed-sun-twice',
    enabled: true,
  },
  {
    brand: 'DESCENTE',
    category: 'sports',
    subcategory: '户外',
    region: 'cn',
    sourceType: 'Official Site',
    listUrl: 'https://allterrain.descente.com/',
    sourceLabel: 'DESCENTE ALLTERRAIN 官方网站',
    fetchMode: 'html',
    products: ['ALLTERRAIN', 'ALLTERRAIN 81', 'MIZUSAWA DOWN'],
    keywords: ['ALLTERRAIN', '81', 'DESCENTE', '户外'],
    imageStrategy: 'product-page',
    cadence: 'wed-sun-twice',
    enabled: true,
  },
  {
    brand: 'Apple',
    category: 'digital',
    subcategory: '手机',
    region: 'cn',
    sourceType: 'Official News',
    listUrl: 'https://www.apple.com.cn/cn/newsroom/topics/iphone/',
    sourceLabel: 'Apple 中国大陆新闻稿',
    fetchMode: 'html',
    products: ['iPhone 17e', 'A19 芯片', '48MP 双摄系统'],
    keywords: ['iPhone', 'introduces', 'newsroom'],
    imageStrategy: 'product-page',
    cadence: 'wed-sun-twice',
    enabled: true,
  },
  {
    brand: 'Microsoft Surface',
    category: 'digital',
    subcategory: '电脑',
    region: 'cn',
    sourceType: 'Official Site',
    listUrl: 'https://www.microsoft.com/zh-cn/surface/business/surface-laptop-6',
    sourceLabel: 'Microsoft Surface 中国官网',
    fetchMode: 'browser',
    products: ['Surface Laptop 6', 'Copilot+ PC', 'Intel Core Ultra'],
    keywords: ['Surface Laptop 6', 'AI PC', 'Copilot'],
    imageStrategy: 'page-screenshot',
    cadence: 'wed-sun-twice',
    enabled: true,
  },
  // ---- LEGO 乐高 ---- 
  {
    brand: 'LEGO',
    category: 'toys',
    subcategory: '乐高',
    region: 'cn',
    sourceType: 'Official Site',
    listUrl: 'https://www.lego.com/zh-cn/categories/new-sets-and-products',
    sourceLabel: 'LEGO 新品套装',
    fetchMode: 'html',
    products: ['LEGO', '积木', '新品'],
    keywords: ['LEGO', '乐高', '积木', '新套装'],
    imageStrategy: 'product-page',
    cadence: 'daily',
    enabled: true,
  },
  // ---- Fendi 芬迪 ----
  {
    brand: 'Fendi',
    category: 'luxury',
    subcategory: '包袋',
    region: 'cn',
    sourceType: 'New Arrivals',
    listUrl: 'https://www.fendi.cn/women/featured/new.html',
    sourceLabel: 'Fendi 中国官网女士新品',
    fetchMode: 'html',
    products: ['Baguette', 'Peekaboo', '手袋', '新品'],
    keywords: ['女士', 'Baguette', 'Peekaboo', '手袋'],
    imageStrategy: 'product-page',
    cadence: 'wed-sun-twice',
    enabled: true,
  },
  {
    brand: 'Fendi',
    category: 'luxury',
    subcategory: '包袋',
    region: 'cn',
    sourceType: 'New Arrivals',
    listUrl: 'https://www.fendi.cn/man/featured/new.html',
    sourceLabel: 'Fendi 中国官网男士新品',
    fetchMode: 'html',
    products: ['Peekaboo', 'Baguette', '手袋', '男士新品'],
    keywords: ['男士', 'Peekaboo', 'Baguette', '手袋'],
    imageStrategy: 'product-page',
    cadence: 'wed-sun-twice',
    enabled: true,
  },
  // ---- Bottega Veneta 葆蝶家 ----
  {
    brand: 'Bottega Veneta',
    category: 'luxury',
    subcategory: '包袋',
    region: 'cn',
    sourceType: 'New Arrivals',
    listUrl: 'https://www.bottegaveneta.cn/categories/bv-newarrivals.html',
    sourceLabel: 'Bottega Veneta 中国官网全新上市',
    fetchMode: 'html',
    products: ['Andiamo', 'Sardine', 'Jodie', '手袋'],
    keywords: ['全新', 'Andiamo', 'Sardine', '手袋'],
    imageStrategy: 'product-page',
    cadence: 'wed-sun-twice',
    enabled: true,
  },
  // ---- Saint Laurent 圣罗兰 ----
  {
    brand: 'Saint Laurent',
    category: 'luxury',
    subcategory: '包袋',
    region: 'cn',
    sourceType: 'New Arrivals',
    listUrl: 'https://www.ysl.cn/categories/highlights/handbags/hb-new-arrivals.html',
    sourceLabel: 'Saint Laurent 中国官网手袋新品',
    fetchMode: 'html',
    products: ['LE 5 À 7', 'NIKI', 'JAMIE', '手袋'],
    keywords: ['新品', '手袋', 'LE 5 À 7', 'NIKI'],
    imageStrategy: 'product-page',
    cadence: 'wed-sun-twice',
    enabled: true,
  },
  // ---- Gucci 古驰 ----
  {
    brand: 'Gucci',
    category: 'luxury',
    subcategory: '包袋',
    region: 'cn',
    sourceType: 'New Arrivals',
    listUrl: 'https://www.gucci.cn/zh/ca/whats-new/new-in/this-week-women',
    sourceLabel: 'Gucci 中国官网女士新品',
    fetchMode: 'html',
    products: ['GG Marmont', 'Jackie 1961', 'Horsebit 1955', '手袋'],
    keywords: ['女士新品', 'GG Marmont', 'Jackie', '手袋'],
    imageStrategy: 'product-page',
    cadence: 'wed-sun-twice',
    enabled: true,
  },
  {
    brand: 'Gucci',
    category: 'luxury',
    subcategory: '包袋',
    region: 'cn',
    sourceType: 'New Arrivals',
    listUrl: 'https://www.gucci.cn/zh/ca/whats-new/new-in/this-week-men',
    sourceLabel: 'Gucci 中国官网男士新品',
    fetchMode: 'html',
    products: ['Ophidia', 'GG Supreme', '男士手袋', '箱包'],
    keywords: ['男士新品', 'Ophidia', 'GG Supreme', '箱包'],
    imageStrategy: 'product-page',
    cadence: 'wed-sun-twice',
    enabled: true,
  },
  // ---- Celine 思琳 ----
  {
    brand: 'Celine',
    category: 'luxury',
    subcategory: '包袋',
    region: 'cn',
    sourceType: 'New Arrivals',
    listUrl: 'https://www.celine.cn/celine-new',
    sourceLabel: 'Celine 中国官网新品',
    fetchMode: 'html',
    products: ['TRIOMPHE', 'LUGGAGE', 'NINO', '手袋'],
    keywords: ['新品', 'TRIOMPHE', 'LUGGAGE', '手袋'],
    imageStrategy: 'product-page',
    cadence: 'wed-sun-twice',
    enabled: true,
  },
  {
    brand: 'Celine',
    category: 'luxury',
    subcategory: '包袋',
    region: 'cn',
    sourceType: 'New Arrivals',
    listUrl: 'https://www.celine.cn/celine-women/bags/new',
    sourceLabel: 'Celine 中国官网女士手袋新品',
    fetchMode: 'html',
    products: ['TRIOMPHE手袋', '凯旋门', '迷你手袋', '女士新品'],
    keywords: ['TRIOMPHE', '凯旋门', '手袋', '女士新品'],
    imageStrategy: 'product-page',
    cadence: 'wed-sun-twice',
    enabled: true,
  },
  // ---- Alexander McQueen 麦昆 ----
  {
    brand: 'Alexander McQueen',
    category: 'luxury',
    subcategory: '包袋',
    region: 'cn',
    sourceType: 'New Arrivals',
    listUrl: 'https://www.alexandermcqueen.cn/categories/women/shopby-women/womennewin.html',
    sourceLabel: 'McQueen 中国官网女士新品',
    fetchMode: 'html',
    products: ['手袋', '运动鞋', '成衣', '配饰'],
    keywords: ['新品', '手袋', '运动鞋', '女士'],
    imageStrategy: 'product-page',
    cadence: 'wed-sun-twice',
    enabled: true,
  },
  {
    brand: 'Alexander McQueen',
    category: 'luxury',
    subcategory: '包袋',
    region: 'cn',
    sourceType: 'New Arrivals',
    listUrl: 'https://www.alexandermcqueen.cn/categories/men/shopby-m/mennewin.html',
    sourceLabel: 'McQueen 中国官网男士新品',
    fetchMode: 'html',
    products: ['手袋', '运动鞋', '成衣', '配饰'],
    keywords: ['新品', '手袋', '运动鞋', '男士'],
    imageStrategy: 'product-page',
    cadence: 'wed-sun-twice',
    enabled: true,
  },
  // ---- Miu Miu 缪缪 ----
  {
    brand: 'Miu Miu',
    category: 'luxury',
    subcategory: '包袋',
    region: 'cn',
    sourceType: 'New Arrivals',
    listUrl: 'https://www.miumiu.cn/cn/zh/new-arrivals/c/10200CN',
    sourceLabel: 'Miu Miu 中国官网新品',
    fetchMode: 'html',
    products: ['手袋', '包袋', '成衣', '鞋履'],
    keywords: ['新品', '新款', '手袋', '包袋'],
    imageStrategy: 'product-page',
    cadence: 'wed-sun-twice',
    enabled: true,
  },
  {
    brand: 'Miu Miu',
    category: 'luxury',
    subcategory: '包袋',
    region: 'cn',
    sourceType: 'New Arrivals',
    listUrl: 'https://www.miumiu.cn/cn/zh/new-arrivals/bags/c/10201CN',
    sourceLabel: 'Miu Miu 中国官网包袋新品',
    fetchMode: 'html',
    products: ['手袋', '包袋', 'Matelassé', '迷你包'],
    keywords: ['新品', '包袋', 'Matelassé', '手袋'],
    imageStrategy: 'product-page',
    cadence: 'wed-sun-twice',
    enabled: true,
  },
  // ---- Xiaomi 小米 ----
  {
    brand: 'Xiaomi',
    category: 'digital',
    subcategory: '手机',
    region: 'cn',
    sourceType: 'Official Site',
    listUrl: 'https://www.mi.com/shop',
    sourceLabel: '小米官方商城',
    fetchMode: 'html',
    products: ['Xiaomi 17', 'REDMI Note 17', 'REDMI K90', 'Xiaomi Pad'],
    keywords: ['新品', '首发', '小米', 'REDMI', 'Xiaomi'],
    imageStrategy: 'product-page',
    cadence: 'wed-sun-twice',
    enabled: true,
  },
  // ---- OPPO ----
  {
    brand: 'OPPO',
    category: 'digital',
    subcategory: '手机',
    region: 'cn',
    sourceType: 'Official Site',
    listUrl: 'https://www.oppo.com/cn/smartphones/',
    sourceLabel: 'OPPO 中国官网手机',
    fetchMode: 'html',
    products: ['Find X9', 'Find N6', 'Reno16', 'OPPO Pad', 'OPPO Watch'],
    keywords: ['新品', 'Reno', 'Find X', 'OPPO'],
    imageStrategy: 'product-page',
    cadence: 'wed-sun-twice',
    enabled: true,
  },
  // ---- vivo ----
  {
    brand: 'vivo',
    category: 'digital',
    subcategory: '手机',
    region: 'cn',
    sourceType: 'Official Site',
    listUrl: 'https://www.vivo.com.cn/',
    sourceLabel: 'vivo 中国官网',
    fetchMode: 'html',
    products: ['X300', 'X Fold6', 'S60', 'iQOO 15', 'vivo Pad6'],
    keywords: ['新品', '首发', 'X300', 'S60', 'X Fold'],
    imageStrategy: 'product-page',
    cadence: 'wed-sun-twice',
    enabled: true,
  },
  // ---- YONEX ----
  {
    brand: 'YONEX',
    category: 'sports',
    subcategory: '网球',
    region: 'cn',
    sourceType: 'Official News',
    listUrl: 'https://www.yonex.cn/home/index/news',
    sourceLabel: 'YONEX 中国官网最新动态',
    fetchMode: 'html',
    products: ['网球拍', '羽毛球拍', '高尔夫', '滑雪板', '运动鞋'],
    keywords: ['新品', '发售', '上市', '发布'],
    imageStrategy: 'product-page',
    cadence: 'wed-sun-twice',
    enabled: true,
  },
  // ---- Apple ----
  {
    brand: 'Apple',
    category: 'digital',
    subcategory: '手机',
    region: 'cn',
    sourceType: 'Official Site',
    listUrl: 'https://www.apple.com.cn/iphone/',
    sourceLabel: 'Apple 中国官网 iPhone',
    fetchMode: 'html',
    products: ['iPhone 17', 'iPhone 17 Pro', 'iPhone Air', 'iPhone 17e'],
    keywords: ['新品', 'iPhone', '发售', '上市'],
    imageStrategy: 'product-page',
    cadence: 'wed-sun-twice',
    enabled: true,
  },
  // ---- Lenovo 联想 ----
  {
    brand: 'Lenovo',
    category: 'digital',
    subcategory: '电脑',
    region: 'cn',
    sourceType: 'Official Site',
    listUrl: 'https://shop.lenovo.com.cn/',
    sourceLabel: '联想官方商城',
    fetchMode: 'html',
    products: ['拯救者', 'ThinkPad', 'Yoga', '小新', 'YOGA'],
    keywords: ['新品', '首发', '拯救者', 'ThinkPad', 'Yoga'],
    imageStrategy: 'product-page',
    cadence: 'wed-sun-twice',
    enabled: true,
  },
  // ---- Sony ----
  {
    brand: 'Sony',
    category: 'digital',
    subcategory: '相机',
    region: 'cn',
    sourceType: 'Official News',
    listUrl: 'https://www.sony.com.cn/content/sonyportal/zh-cn/cms/newscenter/product.html',
    sourceLabel: '索尼中国产品新闻',
    fetchMode: 'html',
    products: ['Alpha', '微单', 'WH-1000XM', 'PS5', '电视'],
    keywords: ['发布', '上市', '新品', '索尼'],
    imageStrategy: 'product-page',
    cadence: 'wed-sun-twice',
    enabled: true,
  },
  // ---- Steam (Valve) 游戏平台 [DISABLED] ----
  {
    brand: 'Steam',
    category: 'digital',
    subcategory: '游戏平台',
    region: 'cn',
    sourceType: 'New Arrivals',
    listUrl: 'https://store.steampowered.com/search/?sort_by=Released_DESC&supportedlang=schinese&os=win',
    sourceLabel: 'Steam 最新发布游戏',
    fetchMode: 'html',
    products: ['Steam', 'PC游戏', '新游', 'Valve'],
    keywords: ['Steam', '游戏', '新游戏', 'PC'],
    imageStrategy: 'product-page',
    cadence: 'wed-sun-twice',
    enabled: false,
  },
  // ---- Xbox (Microsoft) 游戏平台 [DISABLED] ----
  {
    brand: 'Xbox',
    category: 'digital',
    subcategory: 'Xbox游戏',
    region: 'cn',
    sourceType: 'New Arrivals',
    listUrl: 'https://www.xbox.com/zh-CN/games/browse',
    sourceLabel: 'Xbox 游戏列表',
    fetchMode: 'html',
    products: ['Xbox', '游戏', 'Game Pass', '微软'],
    keywords: ['Xbox', '游戏', '微软', '主机'],
    imageStrategy: 'product-page',
    cadence: 'wed-sun-twice',
    enabled: false,
  },
  // ---- PlayStation (Sony) 游戏平台 [DISABLED] ----
  {
    brand: 'PlayStation',
    category: 'digital',
    subcategory: 'PS5游戏',
    region: 'cn',
    sourceType: 'New Arrivals',
    listUrl: 'https://www.playstation.com/zh-hans-cn/ps5/games/',
    sourceLabel: 'PlayStation PS5 游戏',
    fetchMode: 'html',
    products: ['PS5', 'PlayStation', '游戏', '索尼'],
    keywords: ['PS5', 'PlayStation', '游戏', '主机'],
    imageStrategy: 'product-page',
    cadence: 'wed-sun-twice',
    enabled: false,
  },
  // ---- EA (Electronic Arts) 游戏发行商 [DISABLED] ----
  {
    brand: 'EA',
    category: 'digital',
    subcategory: 'EA游戏',
    region: 'cn',
    sourceType: 'Official Site',
    listUrl: 'https://www.ea.com/zh-cn/games/library',
    sourceLabel: 'EA 游戏库',
    fetchMode: 'html',
    products: ['EA', 'FIFA', '战地', '极品飞车'],
    keywords: ['EA', '游戏', 'Electronic Arts', 'EA Sports'],
    imageStrategy: 'product-page',
    cadence: 'wed-sun-twice',
    enabled: false,
  },
  // ---- NVIDIA GeForce 游戏显卡新闻 ----
  {
    brand: 'NVIDIA',
    category: 'digital',
    subcategory: '显卡',
    region: 'cn',
    sourceType: 'Official News',
    listUrl: 'https://www.nvidia.cn/geforce/news/',
    sourceLabel: 'NVIDIA GeForce 新闻',
    fetchMode: 'html',
    products: ['GeForce', 'RTX', 'DLSS', '显卡'],
    keywords: ['GeForce', 'RTX', '显卡', 'NVIDIA'],
    imageStrategy: 'page-screenshot',
    cadence: 'wed-sun-twice',
    enabled: true,
  },
  // ---- ROG (ASUS 玩家国度) 游戏硬件 ----
  {
    brand: 'ROG',
    category: 'digital',
    subcategory: '游戏硬件',
    region: 'cn',
    sourceType: 'Official Site',
    listUrl: 'https://rog.asus.com.cn/',
    sourceLabel: 'ROG 玩家国度官网',
    fetchMode: 'html',
    products: ['ROG', '笔记本', '主板', '显卡'],
    keywords: ['ROG', '玩家国度', '游戏本', '电竞'],
    imageStrategy: 'product-page',
    cadence: 'wed-sun-twice',
    enabled: true,
  },
]

function uniqueKeywords(story: Story) {
  return Array.from(new Set([story.subcategory, ...story.products.slice(0, 3)])).slice(0, 4)
}

function inferFetchMode(story: Story): BrandSourceRule['fetchMode'] {
  if (
    story.brand === "Arc'teryx" ||
    story.brand === 'Hermes' ||
    story.brand === 'Wilson' ||
    story.brand === 'Microsoft Surface'
  ) {
    return 'browser'
  }

  return 'html'
}

function inferImageStrategy(story: Story): BrandSourceRule['imageStrategy'] {
  if (story.sourceType === 'Official News') {
    return 'page-screenshot'
  }

  if (story.sourceUrl === 'https://www.shiseido.com.cn/' || story.sourceUrl.endsWith('.com.cn/')) {
    return 'homepage-module'
  }

  return 'product-page'
}

function buildRuleFromStory(story: Story): BrandSourceRule {
  let listUrl = story.sourceUrl
  let sourceLabel = story.sourceLabel

  if (story.brand === 'Bobbi Brown') {
    listUrl = 'https://www.bobbibrown.com.cn/'
    sourceLabel = 'Bobbi Brown 中国官网首页'
  } else if (story.brand === 'Clinique') {
    listUrl = 'https://www.clinique.com.cn/'
    sourceLabel = 'Clinique 中国官网首页'
  } else if (story.brand === 'Estée Lauder') {
    listUrl = 'https://www.esteelauder.com.cn/'
    sourceLabel = 'Estée Lauder 中国官网首页'
  } else if (story.brand === 'La Mer') {
    listUrl = 'https://www.lamer.com.cn/'
    sourceLabel = 'La Mer 中国官网首页'
  } else if (story.brand === 'Chanel' && story.subcategory === '腕表') {
    listUrl = 'https://www.chanel.cn/cn/watches/'
    sourceLabel = '香奈儿中国官网腕表频道'
  } else if (story.brand === 'CHANEL Beauty') {
    listUrl = 'https://www.chanel.cn/cn/fragrance/'
    sourceLabel = 'CHANEL Beauty 中国官网香氛'
  } else if (story.brand === 'Hermès Beauty') {
    listUrl = 'https://www.hermes.cn/cn/en/category/fragrances/'
    sourceLabel = 'Hermès Beauty 香氛'
  } else if (story.brand === 'DESCENTE') {
    listUrl = 'https://allterrain.descente.com/'
    sourceLabel = 'DESCENTE ALLTERRAIN 官方网站'
  } else if (story.brand === 'ASICS') {
    listUrl = 'https://www.asics.com.cn/'
    sourceLabel = 'ASICS 中国官网首页'
  } else if (story.brand === 'Wilson') {
    listUrl = 'https://www.wilson.com/en-us/tennis'
    sourceLabel = 'Wilson Tennis'
  } else if (story.brand === 'Prada') {
    sourceLabel = 'Prada 中国官网已验证产品页'
  } else if (story.brand === 'Prada Beauty') {
    sourceLabel = 'Prada Beauty 中国官网已验证香氛页'
  } else if (story.brand === 'Dior') {
    sourceLabel = 'Dior 中国官网已验证产品页'
  } else if (story.brand === 'Dior Beauty') {
    listUrl = 'https://www.dior.com/en_us/beauty/page/whats-new.html'
    sourceLabel = "Dior Beauty What's New"
  } else if (story.brand === 'Samsung') {
    listUrl = 'https://www.samsung.com/cn/'
    sourceLabel = '三星中国官网首页'
  }

  return {
    brand: story.brand,
    category: story.category,
    subcategory: story.subcategory,
    region: 'cn',
    sourceType: story.sourceType,
    listUrl,
    sourceLabel,
    fetchMode: inferFetchMode(story),
    products: story.products,
    keywords: uniqueKeywords(story),
    imageStrategy: inferImageStrategy(story),
    cadence: 'wed-sun-twice',
    enabled: true,
  }
}

function pickLatestStoryPerBrandAndSubcategory(stories: Story[]) {
  const latestByKey = new Map<string, Story>()

  for (const story of stories) {
    const key = `${story.brand}::${story.subcategory}`
    const existing = latestByKey.get(key)
    if (!existing || story.publishedAt > existing.publishedAt) {
      latestByKey.set(key, story)
    }
  }

  return latestByKey
}

const staticStories = [...luxuryNews, ...beautyNews, ...sportsNews, ...digitalNews, ...webgamesNews]
const explicitBrandKeys = new Set(coreBrandSources.map((source) => `${source.brand}::${source.subcategory}`))
const latestStoriesByBrandAndSubcategory = pickLatestStoryPerBrandAndSubcategory(staticStories)

const derivedBrandSources = Array.from(latestStoriesByBrandAndSubcategory.values())
  .filter((story) => !explicitBrandKeys.has(`${story.brand}::${story.subcategory}`))
  .map(buildRuleFromStory)
  .sort((left, right) => {
    if (left.category === right.category) {
      const brandCompare = left.brand.localeCompare(right.brand)
      if (brandCompare !== 0) {
        return brandCompare
      }

      return left.subcategory.localeCompare(right.subcategory)
    }

    return left.category.localeCompare(right.category)
  })

export const brandSources: BrandSourceRule[] = [...coreBrandSources, ...derivedBrandSources]

export function getEnabledBrandSources() {
  return brandSources.filter((source) => source.enabled)
}
